---
# Nginx v-host files
nginx_configuration_files:
  - ["keycloak-vhost.conf.j2", "keycloak-vhost.conf"]


# Generate and paste the crt.pem and key.pem into files folder if you want to use ssl configuration
# Give the files name 
#  example:
#nginx_certificate_file: cert.pem
#nginx_key_file: key.pem

nginx_certificate_file:
# Nginx certificate key file
nginx_key_file:
