---

- name: Ensures the keycloak cert directory exists.
  file: path='{{keycloak_location}}/{{keycloak_folder_name}}/cert' state=directory

- name: Copy certificate file.
  copy:
    # remote_src: yes
    src: "{{keycloak_credential_file.certificate_file}}"
    dest: "{{keycloak_location}}/{{keycloak_folder_name}}/cert/{{keycloak_credential_file.certificate_file}}"
  when: keycloak_credential_file.certificate_file is defined and keycloak_credential_file.certificate_file != ""

- name: Copy key file.
  copy:
    # remote_src: yes
    src: "{{keycloak_credential_file.key_file}}"
    dest: "{{keycloak_location}}/{{keycloak_folder_name}}/cert/{{keycloak_credential_file.key_file}}"
  when: keycloak_credential_file.key_file is defined and keycloak_credential_file.key_file != ""