---
- name: Ensure postgres python packages are present.
  package:
    name: python-psycopg2
  become: yes
  tags:
  - packages
  - root-task

# postgres requires commands (like db creation) to be executed as local user 'postgres' per default
# -> we are not able to use this procedure, because of the 'become un priv user problem' in ansible
# switching the auth-method from peer is no option either
# -> our procedure: set postgres-pw for db configuration and remove afterwards
- name: Set postgres password.
  become: yes
  shell: 'su postgres -c "psql --command=\"ALTER USER postgres WITH PASSWORD ''{{keycloak_postgres_tmp_root_password}}'';\""'
  tags:
  - packages
  - root-task

- name: Create a new database for keycloak.
  postgresql_db:
    login_password: '{{keycloak_postgres_tmp_root_password}}'
    login_host: localhost
    name: '{{keycloak_db.name}}'
    encoding: 'utf8'
    state: present
  become: yes
  tags:
  - root-task

- name: Create keycloak database user
  postgresql_user:
    login_password: '{{keycloak_postgres_tmp_root_password}}'
    login_host: localhost
    db: '{{keycloak_db.name}}'
    name: '{{keycloak_db.user}}'
    password: '{{keycloak_db.password}}'
    priv: 'ALL'
  become: yes
  tags:
  - root-task

- name: Configure keycloak database backup user
  postgresql_user:
    login_password: '{{keycloak_postgres_tmp_root_password}}'
    login_host: localhost
    db: '{{keycloak_db.name}}'
    name: '{{keycloak_backup_db_user}}'
    password: '{{ keycloak_backup_db_password }}'
    priv: 'ALL'
    role_attr_flags: SUPERUSER
    state: '{{ keycloak_backup_process_state }}'
  become: yes
  tags:
  - root-task

- name: remove postgres password
  become: yes
  shell: 'su postgres -c "psql --command=\"ALTER USER postgres WITH PASSWORD null;\""'
  tags:
  - packages
  - root-task