---
# keycloak host
keycloak_host: 192.168.98.112

# keycloak base directory
keycloak_base_dir: "{{ansible_env.HOME}}"

# keycloak version 
keycloak_version: 21.1.1

# initial user administration
keycloak_initial_admin:
  username: admin
  password: ch@ngEme

# keycloak database configuration
keycloak_db:
  name: keycloak
  user: keycloak
  password: keycloak

# keycloak port
keycloak_http_port: 8008
#  keycloak relative path, this will be used also in reverse proxy nginx
keycloak_http_relative_path: keycloak