---

- name: Ensures the nginx certs directory exists.
  file: path='/etc/nginx/certs/' state=directory

- debug:
    var: nginx_certificate_file == None
- name: Copy certificate file.
  copy:
    # remote_src: yes
    src: "{{nginx_certificate_file}}"
    dest: "/etc/nginx/certs/{{nginx_certificate_file}}"
  when: nginx_certificate_file is defined and nginx_certificate_file != "" and nginx_certificate_file != None

- name: Copy key file.
  copy:
    # remote_src: yes
    src: "{{nginx_key_file}}"
    dest: "/etc/nginx/certs/{{nginx_key_file}}"
  when: nginx_key_file is defined and nginx_key_file != "" and nginx_key_file != None

- name: Set keycloak_protocol based on Cert.
  set_fact:
    keycloak_protocol: https
  when: (nginx_certificate_file is defined and nginx_certificate_file != "" and nginx_certificate_file != None) and 
        (nginx_key_file is defined and nginx_key_file != "" and nginx_key_file != None)