---
#  nginx-extras is same as nginx but more rich with features
- name: Install nginx-extras.
  apt:
    name: nginx-extras
    update_cache: yes
    state: present
  become: yes
  no_log: true
  tags:
    - packages
    - root-task
    - nginx

- name: Configure nginx.conf.
  become: true
  template:
    src: "nginx.conf"
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
  tags:
    - packages
    - nginx

- name: Remove the default configuration.
  become: yes
  file:
    path: "/etc/nginx/{{item}}/default"
    state: absent
  with_items:
    - sites-enabled
    - sites-available
  notify:
    - restart nginx
  tags:
    - packages
    - nginx

- name: Copy nginx config file.
  become: yes
  template:
    src: "{{item[0]}}"
    dest: /etc/nginx/sites-available/{{item[1]}}
    force: yes
  loop: "{{ nginx_configuration_files | default([], true) }}"
  notify:
    - restart nginx
  tags:
    - packages
    - nginx

- name: Enable configurations.
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{item[1]}}"
    dest: "/etc/nginx/sites-enabled/{{item[1]}}"
    state: link
    # force: yes
  loop: "{{ nginx_configuration_files | default([], true) }}"
  notify:
    - restart nginx
  tags:
    - packages
    - nginx

- name: Force nginx notified handlers to run before we countinue with other tasks
  meta: flush_handlers
