
- hosts: all
  roles:
  - role: geerlingguy.java
    become: yes
    tags:
      - java
  - role: postgres
    when: keycloak_db_type is defined and keycloak_db_type == "postgres"
    tags:
      - postgres
  - role: nginx
    tags:
      - nginx
  - role: keycloak
    become: yes
    tags:
      - keycloak
    